logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
      user.name: ${security.user.name}
      user.password: ${security.user.password}

  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

management:
  context-path: /mgmt


security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current